epochs: 10
batch_size: 4
max_seq_length: 256
pooling: 'cls'
dropout: 0.1
output_emb_size: 256
learning_rate: 1e-5
warmup_proportion: 0.1
bertadam: False


best_model: 'few_shot_classification_best'
data_path: '/media/mesie/F0E66F06E66ECC82/数据/paddle/baike_qa_multilabel'
model_path: '/media/mesie/F0E66F06E66ECC82/model/ernie-3.0-medium-zh'
#model_path: '/home/mesie/python/aia-nlp-service/lib/pretrained/bert-base-chinese'
#model_path: '/home/mesie/python/aia-nlp-service/lib/pretrained/albert_chinese_base'